In [ ]:
import numpy as np
import pandas as pd
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,GRU
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [ ]:
df=pd.read_csv("./drive/MyDrive/MutationPred.csv")

In [ ]:
v=df.groupby(["Variant"])

In [ ]:
al=v.get_group("alpha")
al

Unnamed: 0  ... Variant
0              0  ...   alpha
1              1  ...   alpha
2              2  ...   alpha
3              3  ...   alpha
4              4  ...   alpha
...          ...  ...     ...
1995        1995  ...   alpha
1996        1996  ...   alpha
1997        1997  ...   alpha
1998        1998  ...   alpha
1999        1999  ...   alpha

[2000 rows x 4 columns]

In [ ]:
be=v.get_group("beta")
be

Unnamed: 0  ... Variant
2000        2000  ...    beta
2001        2001  ...    beta
2002        2002  ...    beta
2003        2003  ...    beta
2004        2004  ...    beta
...          ...  ...     ...
3495        3495  ...    beta
3496        3496  ...    beta
3497        3497  ...    beta
3498        3498  ...    beta
3499        3499  ...    beta

[1500 rows x 4 columns]

In [ ]:
ga=v.get_group("gamma")
ga

Unnamed: 0  ... Variant
3500        3500  ...   gamma
3501        3501  ...   gamma
3502        3502  ...   gamma
3503        3503  ...   gamma
3504        3504  ...   gamma
...          ...  ...     ...
4995        4995  ...   gamma
4996        4996  ...   gamma
4997        4997  ...   gamma
4998        4998  ...   gamma
4999        4999  ...   gamma

[1500 rows x 4 columns]

In [ ]:
de=v.get_group("delta")
de

Unnamed: 0  ... Variant
5000        5000  ...   delta
5001        5001  ...   delta
5002        5002  ...   delta
5003        5003  ...   delta
5004        5004  ...   delta
...          ...  ...     ...
6995        6995  ...   delta
6996        6996  ...   delta
6997        6997  ...   delta
6998        6998  ...   delta
6999        6999  ...   delta

[2000 rows x 4 columns]

In [ ]:
ka=v.get_group("kappa")
ka

Unnamed: 0  ... Variant
9352         9352  ...   kappa
9353         9353  ...   kappa
9354         9354  ...   kappa
9355         9355  ...   kappa
9356         9356  ...   kappa
...           ...  ...     ...
10164       10164  ...   kappa
10165       10165  ...   kappa
10166       10166  ...   kappa
10167       10167  ...   kappa
10168       10168  ...   kappa

[817 rows x 4 columns]

In [ ]:
et=v.get_group("eta")
et

Unnamed: 0  ... Variant
7000        7000  ...     eta
7001        7001  ...     eta
7002        7002  ...     eta
7003        7003  ...     eta
7004        7004  ...     eta
...          ...  ...     ...
9347        9347  ...     eta
9348        9348  ...     eta
9349        9349  ...     eta
9350        9350  ...     eta
9351        9351  ...     eta

[2352 rows x 4 columns]

In [ ]:
om=v.get_group("omicron")
om

Unnamed: 0  ...  Variant
10169       10169  ...  omicron
10170       10170  ...  omicron
10171       10171  ...  omicron
10172       10172  ...  omicron
10173       10173  ...  omicron
10174       10174  ...  omicron
10175       10175  ...  omicron
10176       10176  ...  omicron
10177       10177  ...  omicron

[9 rows x 4 columns]

In [ ]:
al1=al.sample(100,random_state=100)
be1=be.sample(100,random_state=100)
ga1=ga.sample(100,random_state=100)
de1=de.sample(100,random_state=100)
et1=et.sample(100,random_state=100)
ka1=ka.sample(100,random_state=100)
df_mer=[al1,be1,ga1,de1,ka1,et1,om]
data=pd.concat(df_mer,ignore_index=True)
data=data.iloc[:,1:]

In [ ]:
data

Accession                                           Sequence  Variant
0    OK512132.1  CTTTC TTTCG TTCGA TCGAT CGATC GATCT ATCTC TCTC...    alpha
1    OK192162.1  CCAAC CAACC AACCA ACCAA CCAAC CAACT AACTT ACTT...    alpha
2    OK191902.1  CCAAC CAACT AACTT ACTTT CTTTC TTTCG TTCGA TCGA...    alpha
3    OL522163.1  TAAAG AAAGG AAGGT AGGTT GGTTT GTTTA TTTAT TTAT...    alpha
4    OK547769.1  TGTGG GTGGC TGGCT GGCTG GCTGT CTGTC TGTCA GTCA...    alpha
..          ...                                                ...      ...
604  OL901854.1  ACCAA CCAAC CAACC AACCA ACCAA CCAAC CAACT AACT...  omicron
605  OL902308.1  CAACT AACTT ACTTT CTTTC TTTCG TTCGA TCGAT CGAT...  omicron
606  OV269084.1  NNNNN NNNNN NNNNN NNNNN NNNNN NNNNN NNNNN NNNN...  omicron
607  OV269229.1  NNNNN NNNNN NNNNN NNNNN NNNNN NNNNN NNNNN NNNN...  omicron
608  OV269330.1  NNNNN NNNNN NNNNN NNNNN NNNNN NNNNN NNNNN NNNN...  omicron

[609 rows x 3 columns]

In [ ]:
x=df["Sequence"].values
x

array(['CTTTC TTTCG TTCGA TCGAT CGATC GATCT ATCTC TCTCT CTCTT TCTTG CTTGT TTGTA TGTAG GTAGA TAGAT AGATC GATCT ATCTG TCTGT CTGTT TGTTC GTTCT TTCTC TCTCT CTCTA TCTAA CTAAA TAAAC AAACG AACGA ACGAA CGAAC GAACT AACTT ACTTT CTTTA TTTAA TTAAA TAAAA AAAAT AAATC AATCT ATCTG TCTGT CTGTG TGTGT GTGTG TGTGG GTGGC TGGCT GGCTG GCTGT CTGTC TGTCA GTCAC TCACT CACTC ACTCG CTCGG TCGGC CGGCT GGCTG GCTGC CTGCA TGCAT GCATG CATGC ATGCT TGCTT GCTTA CTTAG TTAGT TAGTG AGTGC GTGCA TGCAC GCACT CACTC ACTCA CTCAC TCACG CACGC ACGCA CGCAG GCAGT CAGTA AGTAT GTATA TATAA ATAAT TAATT AATTA ATTAA TTAAT TAATA AATAA ATAAC TAACT AACTA ACTAA CTAAT TAATT AATTA ATTAC TTACT TACTG ACTGT CTGTC TGTCG GTCGT TCGTT CGTTG GTTGA TTGAC TGACA GACAG ACAGG CAGGA AGGAC GGACA GACAC ACACG CACGA ACGAG CGAGT GAGTA AGTAA GTAAC TAACT AACTC ACTCG CTCGT TCGTC CGTCT GTCTA TCTAT CTATC TATCT ATCTT TCTTC CTTCT TTCTG TCTGC CTGCA TGCAG GCAGG CAGGC AGGCT GGCTG GCTGC CTGCT TGCTT GCTTA CTTAC TTACG TACGG ACGGT CGGTT GGTTT GTTTC TTTCG TTCGT TCGTC CGTCC GTCCG TC

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
y=df["Variant"].values
y_labeled=le.fit_transform(y)
y_labeled

array([0, 0, 0, ..., 6, 6, 6])

In [ ]:
# one_hot(x[0],100)

In [ ]:
x_encoded= [one_hot(d, 50) for d in x]

In [ ]:
max_length = len(max(x_encoded,key=len))+1
max_length 

30252

In [ ]:
x_padded = pad_sequences(x_encoded, maxlen=max_length, padding='post')
print(x_padded)

[[44  5 44 ...  0  0  0]
 [44  5 44 ...  0  0  0]
 [ 5 25 32 ...  0  0  0]
 ...
 [17 17 17 ...  0  0  0]
 [17 17 17 ...  0  0  0]
 [17 17 17 ...  0  0  0]]


In [ ]:
embeded_vector_size = 1000
model = Sequential()
model.add(Embedding(50, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [ ]:
# Categorical crossentropy

In [ ]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 30252, 1000)       50000     
                                                                 
 flatten (Flatten)           (None, 30252000)          0         
                                                                 
 dense (Dense)               (None, 1)                 30252001  
                                                                 
Total params: 30,302,001
Trainable params: 30,302,001
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
x,y=x_padded,y_labeled

In [ ]:
model.fit(x, y, epochs=5, verbose=0)

In [ ]:
# evaluate the model
loss, accuracy = model.evaluate(x,y)
accuracy